# Generated by Django 5.0.7 on 2024-08-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaiseTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'raisingticket',
            },
        ),
    ]
